import {
  IoGridOutline,
  IoBusinessOutline,
  IoCardOutline,
  IoPeopleCircleOutline,
  IoLayersOutline,
  IoListOutline,
  IoTrendingUpOutline,
  IoSettingsOutline,
  IoShieldCheckmark,
  IoLogOutOutline,
  IoChevronForwardOutline,
  IoConstructOutline,
  IoCloseCircleOutline,
  IoWarningOutline,
  IoAlarmOutline,
  IoPieChartOutline,
  IoWarning,
  IoArrowForwardOutline,
  IoCloseOutline,
  IoPeopleOutline,
  IoHourglassOutline,
  IoBarChartOutline,
  IoTrendingUp,
  IoRefreshCircleOutline,
  IoBanOutline,
  IoInformationCircleOutline,
  IoAttachOutline,
  IoEyeOutline,
  IoDocumentOutline,
  IoCheckmarkOutline,
  IoAlertCircle,
  IoTimeOutline,
  IoPauseCircleOutline,
  IoPlayCircleOutline,
  IoDownloadOutline,
  IoSearchOutline,
  IoChevronBackOutline,
  IoCheckmarkCircleOutline,
  IoLocationOutline,
  IoStorefrontOutline,
  IoCubeOutline,
  IoPersonOutline,
  IoMailOutline,
  IoDocumentTextOutline,
  IoReaderOutline,
  IoCallOutline,
  IoShareSocialOutline,
  IoCashOutline,
  IoLogoFacebook,
  IoLogoInstagram,
  IoLogoLinkedin,
  IoLogoYoutube,
  IoMusicalNotesOutline,
  IoGlobeOutline,
  IoLinkOutline,
  IoCreateOutline,
  IoEyeOffOutline,
  IoCheckmarkCircle,
  IoAddOutline,
  IoBriefcaseOutline,
  IoTrashOutline,
  IoReceiptOutline,
  IoClose,
  IoGiftOutline,
  IoHeadsetOutline,
  IoLockClosedOutline,
  IoArrowBackOutline,
  IoKeyOutline,
  IoMailOpenOutline,
  IoShieldCheckmarkOutline,
  IoEllipseOutline,
} from 'react-icons/io5'

// Maps the original ionicon names (used throughout the markup) to their
// react-icons/io5 equivalents so call sites stay unchanged.
const ICONS = {
  'grid-outline': IoGridOutline,
  'business-outline': IoBusinessOutline,
  'card-outline': IoCardOutline,
  'people-circle-outline': IoPeopleCircleOutline,
  'layers-outline': IoLayersOutline,
  'list-outline': IoListOutline,
  'trending-up-outline': IoTrendingUpOutline,
  'settings-outline': IoSettingsOutline,
  'shield-checkmark': IoShieldCheckmark,
  'log-out-outline': IoLogOutOutline,
  'chevron-forward-outline': IoChevronForwardOutline,
  'construct-outline': IoConstructOutline,
  'close-circle-outline': IoCloseCircleOutline,
  'warning-outline': IoWarningOutline,
  'alarm-outline': IoAlarmOutline,
  'pie-chart-outline': IoPieChartOutline,
  warning: IoWarning,
  'arrow-forward-outline': IoArrowForwardOutline,
  'close-outline': IoCloseOutline,
  'people-outline': IoPeopleOutline,
  'hourglass-outline': IoHourglassOutline,
  'bar-chart-outline': IoBarChartOutline,
  'trending-up': IoTrendingUp,
  'refresh-circle-outline': IoRefreshCircleOutline,
  'ban-outline': IoBanOutline,
  'information-circle-outline': IoInformationCircleOutline,
  'attach-outline': IoAttachOutline,
  'eye-outline': IoEyeOutline,
  'document-outline': IoDocumentOutline,
  'checkmark-outline': IoCheckmarkOutline,
  'alert-circle': IoAlertCircle,
  'time-outline': IoTimeOutline,
  'pause-circle-outline': IoPauseCircleOutline,
  'play-circle-outline': IoPlayCircleOutline,
  'download-outline': IoDownloadOutline,
  'search-outline': IoSearchOutline,
  'chevron-back-outline': IoChevronBackOutline,
  'checkmark-circle-outline': IoCheckmarkCircleOutline,
  'location-outline': IoLocationOutline,
  'storefront-outline': IoStorefrontOutline,
  'cube-outline': IoCubeOutline,
  'person-outline': IoPersonOutline,
  'mail-outline': IoMailOutline,
  'document-text-outline': IoDocumentTextOutline,
  'reader-outline': IoReaderOutline,
  'call-outline': IoCallOutline,
  'share-social-outline': IoShareSocialOutline,
  'cash-outline': IoCashOutline,
  'logo-facebook': IoLogoFacebook,
  'logo-instagram': IoLogoInstagram,
  'logo-linkedin': IoLogoLinkedin,
  'logo-youtube': IoLogoYoutube,
  'musical-notes-outline': IoMusicalNotesOutline,
  'globe-outline': IoGlobeOutline,
  'link-outline': IoLinkOutline,
  'create-outline': IoCreateOutline,
  'eye-off-outline': IoEyeOffOutline,
  'checkmark-circle': IoCheckmarkCircle,
  'add-outline': IoAddOutline,
  'briefcase-outline': IoBriefcaseOutline,
  'trash-outline': IoTrashOutline,
  'receipt-outline': IoReceiptOutline,
  close: IoClose,
  'gift-outline': IoGiftOutline,
  'headset-outline': IoHeadsetOutline,
  'lock-closed-outline': IoLockClosedOutline,
  'arrow-back-outline': IoArrowBackOutline,
  'key-outline': IoKeyOutline,
  'mail-open-outline': IoMailOpenOutline,
  'shield-checkmark-outline': IoShieldCheckmarkOutline,
  'ellipse-outline': IoEllipseOutline,
}

/**
 * Renders an icon from react-icons/io5 by its original ionicon name.
 * The SVG is sized in `em`, so `size` (px) or a Tailwind text-* class
 * controls its dimensions, and colour is inherited via currentColor.
 */
export default function Icon({ name, size, className = '', style = {}, ...rest }) {
  const Cmp = ICONS[name]
  if (!Cmp) {
    if (import.meta.env.DEV) console.warn(`Icon: unknown name "${name}"`)
    return null
  }
  const mergedStyle = size ? { fontSize: `${size}px`, ...style } : style
  return <Cmp className={className} style={mergedStyle} {...rest} />
}
