import {
  IoNotificationsOutline,
  IoLocation,
  IoChevronDown,
  IoChevronForward,
  IoChevronBackOutline,
  IoSearchOutline,
  IoBagHandleOutline,
  IoWalletOutline,
  IoHeartOutline,
  IoHeart,
  IoStarOutline,
  IoStar,
  IoStorefrontOutline,
  IoCubeOutline,
  IoGridOutline,
  IoAppsOutline,
  IoNavigateCircleOutline,
  IoNavigateOutline,
  IoCheckmarkCircleOutline,
  IoCarOutline,
  IoHomeOutline,
  IoCartOutline,
  IoQrCodeOutline,
  IoReceiptOutline,
  IoSettingsOutline,
  IoAddOutline,
  IoRemoveOutline,
  IoPricetagOutline,
  IoInformationCircleOutline,
  // category icons
  IoBasketOutline,
  IoShirtOutline,
  IoHardwareChipOutline,
  IoPhonePortraitOutline,
  IoMedkitOutline,
  IoBedOutline,
  IoSparklesOutline,
  IoCafeOutline,
  IoWineOutline,
  IoFastFoodOutline,
  IoNutritionOutline,
  IoCutOutline,
  IoLeafOutline,
  IoManOutline,
  IoWomanOutline,
  IoFootstepsOutline,
  IoWatchOutline,
  IoLaptopOutline,
  IoHeadsetOutline,
  IoFitnessOutline,
  IoHappyOutline,
  IoRestaurantOutline,
  IoColorPaletteOutline,
  IoWaterOutline,
  IoBrushOutline,
  IoGiftOutline,
  IoTvOutline,
  IoFileTrayStackedOutline,
  // actions / detail / settings / sheets
  IoTrashOutline,
  IoLockClosed,
  IoLockClosedOutline,
  IoArrowForwardOutline,
  IoArrowBackOutline,
  IoChevronForwardOutline,
  IoChevronUp,
  IoShareSocialOutline,
  IoHelpBuoyOutline,
  IoHelpCircleOutline,
  IoChatbubblesOutline,
  IoChatboxEllipsesOutline,
  IoAlertCircleOutline,
  IoAlertCircle,
  IoCloseCircleOutline,
  IoCloseOutline,
  IoArrowUndoOutline,
  IoLogoWhatsapp,
  IoCallOutline,
  IoMailOutline,
  IoPersonOutline,
  IoLocationOutline,
  IoCardOutline,
  IoDocumentTextOutline,
  IoLogOutOutline,
  IoCheckmarkOutline,
  IoCheckmarkCircle,
  IoCreateOutline,
  IoBusinessOutline,
  IoStorefront,
  IoWarningOutline,
  IoShieldCheckmarkOutline,
  IoCashOutline,
} from 'react-icons/io5'

const ICONS = {
  'notifications-outline': IoNotificationsOutline,
  location: IoLocation,
  'chevron-down': IoChevronDown,
  'chevron-forward': IoChevronForward,
  'chevron-back-outline': IoChevronBackOutline,
  'search-outline': IoSearchOutline,
  'bag-handle-outline': IoBagHandleOutline,
  'wallet-outline': IoWalletOutline,
  'heart-outline': IoHeartOutline,
  heart: IoHeart,
  'star-outline': IoStarOutline,
  star: IoStar,
  'storefront-outline': IoStorefrontOutline,
  'cube-outline': IoCubeOutline,
  'grid-outline': IoGridOutline,
  'apps-outline': IoAppsOutline,
  'navigate-circle-outline': IoNavigateCircleOutline,
  'navigate-outline': IoNavigateOutline,
  'checkmark-circle-outline': IoCheckmarkCircleOutline,
  'car-outline': IoCarOutline,
  'home-outline': IoHomeOutline,
  'cart-outline': IoCartOutline,
  'qr-code-outline': IoQrCodeOutline,
  'receipt-outline': IoReceiptOutline,
  'settings-outline': IoSettingsOutline,
  'add-outline': IoAddOutline,
  'remove-outline': IoRemoveOutline,
  'pricetag-outline': IoPricetagOutline,
  'information-circle-outline': IoInformationCircleOutline,
  // categories
  'basket-outline': IoBasketOutline,
  'shirt-outline': IoShirtOutline,
  'hardware-chip-outline': IoHardwareChipOutline,
  'phone-portrait-outline': IoPhonePortraitOutline,
  'medkit-outline': IoMedkitOutline,
  'bed-outline': IoBedOutline,
  'sparkles-outline': IoSparklesOutline,
  'cafe-outline': IoCafeOutline,
  'wine-outline': IoWineOutline,
  'fast-food-outline': IoFastFoodOutline,
  'nutrition-outline': IoNutritionOutline,
  'cut-outline': IoCutOutline,
  'leaf-outline': IoLeafOutline,
  'man-outline': IoManOutline,
  'woman-outline': IoWomanOutline,
  'footsteps-outline': IoFootstepsOutline,
  'watch-outline': IoWatchOutline,
  'laptop-outline': IoLaptopOutline,
  'headset-outline': IoHeadsetOutline,
  'fitness-outline': IoFitnessOutline,
  'happy-outline': IoHappyOutline,
  'restaurant-outline': IoRestaurantOutline,
  'color-palette-outline': IoColorPaletteOutline,
  'water-outline': IoWaterOutline,
  'brush-outline': IoBrushOutline,
  'gift-outline': IoGiftOutline,
  'tv-outline': IoTvOutline,
  'file-tray-stacked-outline': IoFileTrayStackedOutline,
  // actions / detail / settings / sheets
  'trash-outline': IoTrashOutline,
  'lock-closed': IoLockClosed,
  'lock-closed-outline': IoLockClosedOutline,
  'arrow-forward-outline': IoArrowForwardOutline,
  'arrow-back-outline': IoArrowBackOutline,
  'chevron-forward-outline': IoChevronForwardOutline,
  'chevron-up': IoChevronUp,
  'share-social-outline': IoShareSocialOutline,
  'help-buoy-outline': IoHelpBuoyOutline,
  'help-circle-outline': IoHelpCircleOutline,
  'chatbubbles-outline': IoChatbubblesOutline,
  'chatbox-ellipses-outline': IoChatboxEllipsesOutline,
  'alert-circle-outline': IoAlertCircleOutline,
  'alert-circle': IoAlertCircle,
  'close-circle-outline': IoCloseCircleOutline,
  'close-outline': IoCloseOutline,
  'arrow-undo-outline': IoArrowUndoOutline,
  'logo-whatsapp': IoLogoWhatsapp,
  'call-outline': IoCallOutline,
  'mail-outline': IoMailOutline,
  'person-outline': IoPersonOutline,
  'location-outline': IoLocationOutline,
  'card-outline': IoCardOutline,
  'document-text-outline': IoDocumentTextOutline,
  'log-out-outline': IoLogOutOutline,
  'checkmark-outline': IoCheckmarkOutline,
  'checkmark-circle': IoCheckmarkCircle,
  'create-outline': IoCreateOutline,
  'business-outline': IoBusinessOutline,
  storefront: IoStorefront,
  'warning-outline': IoWarningOutline,
  'shield-checkmark-outline': IoShieldCheckmarkOutline,
  'cash-outline': IoCashOutline,
}

export default function Icon({ name, size, className = '', style = {}, ...rest }) {
  const Cmp = ICONS[name]
  if (!Cmp) {
    if (import.meta.env.DEV) console.warn(`Icon: unknown name "${name}"`)
    return null
  }
  const mergedStyle = size ? { fontSize: `${size}px`, ...style } : style
  return <Cmp className={className} style={mergedStyle} {...rest} />
}
