import {
  IoCube,
  IoCubeOutline,
  IoGridOutline,
  IoPricetagsOutline,
  IoPricetagOutline,
  IoSwapHorizontalOutline,
  IoBarcodeOutline,
  IoGlobeOutline,
  IoArrowUndoOutline,
  IoLogOutOutline,
  IoCloseOutline,
  IoCloseCircle,
  IoCloseCircleOutline,
  IoMenuOutline,
  IoChevronForwardOutline,
  IoChevronBackOutline,
  IoChevronDownOutline,
  IoAlertCircleOutline,
  IoArrowDownCircleOutline,
  IoArrowUpCircleOutline,
  IoCheckmarkCircle,
  IoCheckmarkCircleOutline,
  IoCheckmarkDoneOutline,
  IoCheckmarkDoneCircleOutline,
  IoCheckmarkOutline,
  IoEyeOutline,
  IoHourglassOutline,
  IoCashOutline,
  IoCardOutline,
  IoPhonePortraitOutline,
  IoCarOutline,
  IoInformationCircleOutline,
  IoAddOutline,
  IoSearchOutline,
  IoLayersOutline,
  IoCreateOutline,
  IoDocumentTextOutline,
  IoPaperPlaneOutline,
  IoLocationOutline,
  IoBusinessOutline,
  IoStorefrontOutline,
  IoTimeOutline,
  IoWarningOutline,
  IoGitBranchOutline,
  IoTrashOutline,
  IoAlertCircle,
  IoCallOutline,
  IoShieldCheckmarkOutline,
  IoAlbumsOutline,
  IoReaderOutline,
  IoImagesOutline,
  IoImageOutline,
  IoArrowBackOutline,
  IoArrowForwardOutline,
  IoAddCircleOutline,
  IoRemoveOutline,
  IoCartOutline,
  IoPrintOutline,
  IoChatboxEllipsesOutline,
  IoPlayOutline,
  IoScanOutline,
  IoCameraOutline,
  IoFlaskOutline,
  IoSwapVerticalOutline,
  IoTrendingUpOutline,
  IoDownloadOutline,
  IoFileTrayOutline,
  IoEllipsisHorizontalOutline,
} from 'react-icons/io5'

const ICONS = {
  cube: IoCube,
  'cube-outline': IoCubeOutline,
  'grid-outline': IoGridOutline,
  'pricetags-outline': IoPricetagsOutline,
  'pricetag-outline': IoPricetagOutline,
  'swap-horizontal-outline': IoSwapHorizontalOutline,
  'barcode-outline': IoBarcodeOutline,
  'globe-outline': IoGlobeOutline,
  'arrow-undo-outline': IoArrowUndoOutline,
  'log-out-outline': IoLogOutOutline,
  'close-outline': IoCloseOutline,
  'close-circle': IoCloseCircle,
  'close-circle-outline': IoCloseCircleOutline,
  'menu-outline': IoMenuOutline,
  'chevron-forward-outline': IoChevronForwardOutline,
  'chevron-back-outline': IoChevronBackOutline,
  'chevron-down-outline': IoChevronDownOutline,
  'alert-circle-outline': IoAlertCircleOutline,
  'arrow-down-circle-outline': IoArrowDownCircleOutline,
  'arrow-up-circle-outline': IoArrowUpCircleOutline,
  'checkmark-circle': IoCheckmarkCircle,
  'checkmark-circle-outline': IoCheckmarkCircleOutline,
  'checkmark-done-outline': IoCheckmarkDoneOutline,
  'checkmark-done-circle-outline': IoCheckmarkDoneCircleOutline,
  'checkmark-outline': IoCheckmarkOutline,
  'eye-outline': IoEyeOutline,
  'hourglass-outline': IoHourglassOutline,
  'cash-outline': IoCashOutline,
  'card-outline': IoCardOutline,
  'phone-portrait-outline': IoPhonePortraitOutline,
  'car-outline': IoCarOutline,
  'information-circle-outline': IoInformationCircleOutline,
  'add-outline': IoAddOutline,
  'search-outline': IoSearchOutline,
  'layers-outline': IoLayersOutline,
  'create-outline': IoCreateOutline,
  'document-text-outline': IoDocumentTextOutline,
  'paper-plane-outline': IoPaperPlaneOutline,
  'location-outline': IoLocationOutline,
  'business-outline': IoBusinessOutline,
  'storefront-outline': IoStorefrontOutline,
  'time-outline': IoTimeOutline,
  'warning-outline': IoWarningOutline,
  'git-branch-outline': IoGitBranchOutline,
  'trash-outline': IoTrashOutline,
  'alert-circle': IoAlertCircle,
  'call-outline': IoCallOutline,
  'shield-checkmark-outline': IoShieldCheckmarkOutline,
  'albums-outline': IoAlbumsOutline,
  'reader-outline': IoReaderOutline,
  'images-outline': IoImagesOutline,
  'image-outline': IoImageOutline,
  'arrow-back-outline': IoArrowBackOutline,
  'arrow-forward-outline': IoArrowForwardOutline,
  'add-circle-outline': IoAddCircleOutline,
  'remove-outline': IoRemoveOutline,
  'cart-outline': IoCartOutline,
  'print-outline': IoPrintOutline,
  'chatbox-ellipses-outline': IoChatboxEllipsesOutline,
  'play-outline': IoPlayOutline,
  'scan-outline': IoScanOutline,
  'camera-outline': IoCameraOutline,
  'flask-outline': IoFlaskOutline,
  'swap-vertical-outline': IoSwapVerticalOutline,
  'trending-up-outline': IoTrendingUpOutline,
  'download-outline': IoDownloadOutline,
  'file-tray-outline': IoFileTrayOutline,
  'ellipsis-horizontal-outline': IoEllipsisHorizontalOutline,
}

export default function Icon({ name, size, className = '', style = {}, ...rest }) {
  const Cmp = ICONS[name]
  if (!Cmp) {
    if (import.meta.env.DEV) console.warn(`Icon: unknown name "${name}"`)
    return null
  }
  const mergedStyle = size ? { fontSize: `${size}px`, ...style } : style
  return <Cmp className={className} style={mergedStyle} {...rest} />
}
