import {
  IoStorefront,
  IoStorefrontOutline,
  IoGridOutline,
  IoCubeOutline,
  IoCube,
  IoSwapHorizontalOutline,
  IoSwapVerticalOutline,
  IoGlobeOutline,
  IoArrowUndoOutline,
  IoTimeOutline,
  IoReceiptOutline,
  IoLogOutOutline,
  IoMenuOutline,
  IoCloseOutline,
  IoCloseCircle,
  IoCloseCircleOutline,
  IoChevronForwardOutline,
  IoChevronBackOutline,
  IoChevronDownOutline,
  IoNotificationsOutline,
  IoDownloadOutline,
  IoCardOutline,
  IoCashOutline,
  IoQrCodeOutline,
  IoBicycleOutline,
  IoStatsChartOutline,
  IoTrendingUp,
  IoTrendingUpOutline,
  IoCarOutline,
  IoPhonePortraitOutline,
  IoCheckmarkCircle,
  IoCheckmarkCircleOutline,
  IoCheckmarkDoneOutline,
  IoCheckmarkDoneCircleOutline,
  IoCheckmarkOutline,
  IoHourglassOutline,
  IoFlashOutline,
  IoRadioOutline,
  IoLayersOutline,
  IoAlertCircleOutline,
  IoAlertCircle,
  IoInformationCircle,
  IoInformationCircleOutline,
  IoWarning,
  IoWarningOutline,
  IoPaperPlaneOutline,
  IoArrowUpCircleOutline,
  IoArrowDownCircleOutline,
  IoArrowForwardOutline,
  IoArrowBackOutline,
  IoGitBranchOutline,
  IoTrendingDownOutline,
  IoCartOutline,
  IoCreateOutline,
  IoTrashOutline,
  IoEyeOutline,
  IoSearchOutline,
  IoAddOutline,
  IoRemoveOutline,
  IoAddCircleOutline,
  IoLocationOutline,
  IoCallOutline,
  IoShieldCheckmarkOutline,
  IoConstructOutline,
  IoBusinessOutline,
  IoPersonOutline,
  IoStar,
  IoChatboxEllipsesOutline,
  IoBarcodeOutline,
  IoDocumentTextOutline,
  IoScanOutline,
  IoFlaskOutline,
  IoAlbumsOutline,
  IoFileTrayOutline,
  IoEllipsisHorizontalOutline,
  IoCameraOutline,
} from 'react-icons/io5'

const ICONS = {
  storefront: IoStorefront,
  'storefront-outline': IoStorefrontOutline,
  'grid-outline': IoGridOutline,
  'cube-outline': IoCubeOutline,
  cube: IoCube,
  'swap-horizontal-outline': IoSwapHorizontalOutline,
  'swap-vertical-outline': IoSwapVerticalOutline,
  'globe-outline': IoGlobeOutline,
  'arrow-undo-outline': IoArrowUndoOutline,
  'time-outline': IoTimeOutline,
  'receipt-outline': IoReceiptOutline,
  'log-out-outline': IoLogOutOutline,
  'menu-outline': IoMenuOutline,
  'close-outline': IoCloseOutline,
  'close-circle': IoCloseCircle,
  'close-circle-outline': IoCloseCircleOutline,
  'chevron-forward-outline': IoChevronForwardOutline,
  'chevron-back-outline': IoChevronBackOutline,
  'chevron-down-outline': IoChevronDownOutline,
  'notifications-outline': IoNotificationsOutline,
  'download-outline': IoDownloadOutline,
  'card-outline': IoCardOutline,
  'cash-outline': IoCashOutline,
  'qr-code-outline': IoQrCodeOutline,
  'bicycle-outline': IoBicycleOutline,
  'stats-chart-outline': IoStatsChartOutline,
  'trending-up': IoTrendingUp,
  'trending-up-outline': IoTrendingUpOutline,
  'trending-down-outline': IoTrendingDownOutline,
  'cart-outline': IoCartOutline,
  'car-outline': IoCarOutline,
  'phone-portrait-outline': IoPhonePortraitOutline,
  'checkmark-circle': IoCheckmarkCircle,
  'checkmark-circle-outline': IoCheckmarkCircleOutline,
  'checkmark-done-outline': IoCheckmarkDoneOutline,
  'checkmark-done-circle-outline': IoCheckmarkDoneCircleOutline,
  'checkmark-outline': IoCheckmarkOutline,
  'hourglass-outline': IoHourglassOutline,
  'flash-outline': IoFlashOutline,
  'radio-outline': IoRadioOutline,
  'layers-outline': IoLayersOutline,
  'alert-circle-outline': IoAlertCircleOutline,
  'alert-circle': IoAlertCircle,
  'information-circle': IoInformationCircle,
  'information-circle-outline': IoInformationCircleOutline,
  warning: IoWarning,
  'warning-outline': IoWarningOutline,
  'paper-plane-outline': IoPaperPlaneOutline,
  'arrow-up-circle-outline': IoArrowUpCircleOutline,
  'arrow-down-circle-outline': IoArrowDownCircleOutline,
  'arrow-forward-outline': IoArrowForwardOutline,
  'arrow-back-outline': IoArrowBackOutline,
  'git-branch-outline': IoGitBranchOutline,
  'create-outline': IoCreateOutline,
  'trash-outline': IoTrashOutline,
  'eye-outline': IoEyeOutline,
  'search-outline': IoSearchOutline,
  'add-outline': IoAddOutline,
  'remove-outline': IoRemoveOutline,
  'add-circle-outline': IoAddCircleOutline,
  'location-outline': IoLocationOutline,
  'call-outline': IoCallOutline,
  'shield-checkmark-outline': IoShieldCheckmarkOutline,
  'construct-outline': IoConstructOutline,
  'business-outline': IoBusinessOutline,
  'person-outline': IoPersonOutline,
  star: IoStar,
  'chatbox-ellipses-outline': IoChatboxEllipsesOutline,
  'barcode-outline': IoBarcodeOutline,
  'document-text-outline': IoDocumentTextOutline,
  'scan-outline': IoScanOutline,
  'flask-outline': IoFlaskOutline,
  'albums-outline': IoAlbumsOutline,
  'file-tray-outline': IoFileTrayOutline,
  'ellipsis-horizontal-outline': IoEllipsisHorizontalOutline,
  'camera-outline': IoCameraOutline,
}

export default function Icon({ name, size, className = '', style = {}, ...rest }) {
  const Cmp = ICONS[name]
  if (!Cmp) {
    if (import.meta.env.DEV) console.warn(`Icon: unknown name "${name}"`)
    return null
  }
  const mergedStyle = size ? { fontSize: `${size}px`, ...style } : style
  return <Cmp className={className} style={mergedStyle} {...rest} />
}
