import {
  IoStorefront,
  IoStorefrontOutline,
  IoGridOutline,
  IoBusinessOutline,
  IoCubeOutline,
  IoListOutline,
  IoPeopleOutline,
  IoCardOutline,
  IoTrendingUpOutline,
  IoSettingsOutline,
  IoLogOutOutline,
  IoChevronForwardOutline,
  IoChevronBackOutline,
  IoMenuOutline,
  IoCloseOutline,
  IoSearchOutline,
  IoAddOutline,
  IoDownloadOutline,
  IoCashOutline,
  IoReceiptOutline,
  IoGlobeOutline,
  IoCheckmarkCircle,
  IoCheckmarkCircleOutline,
  IoCloseCircleOutline,
  IoAlertCircleOutline,
  IoInformationCircleOutline,
  IoArrowDownCircle,
  IoArrowUpCircle,
  IoArrowDownCircleOutline,
  IoArrowUpCircleOutline,
  IoArrowBackOutline,
  IoTimeOutline,
  IoLayersOutline,
  IoPauseCircleOutline,
  IoEyeOutline,
  IoCreateOutline,
  IoPersonOutline,
  IoPersonCircleOutline,
  IoPersonAddOutline,
  IoQrCodeOutline,
  IoBicycleOutline,
  IoSwapHorizontalOutline,
  IoRefreshOutline,
  IoPrintOutline,
  IoReturnDownBackOutline,
  IoDocumentTextOutline,
  IoCallOutline,
  IoShareSocialOutline,
  IoCameraOutline,
  IoScanOutline,
  IoBarcodeOutline,
  IoTrashOutline,
  IoMailOutline,
  IoLocationOutline,
  IoLogoFacebook,
  IoLogoInstagram,
  IoLogoLinkedin,
  IoLogoYoutube,
  IoMusicalNotesOutline,
  IoPlayCircleOutline,
  IoLocateOutline,
  IoWarningOutline,
  IoArrowUpOutline,
  IoArrowForwardOutline,
  IoMapOutline,
  IoLocation,
  IoSyncOutline,
  IoKeyOutline,
  IoChevronDownOutline,
  IoEllipsisVertical,
  IoAddCircleOutline,
  IoEyeOffOutline,
  IoCloudUploadOutline,
  IoLeafOutline,
  IoRocketOutline,
  IoCheckmarkOutline,
  IoCalendarOutline,
  IoDocumentOutline,
  IoCloseCircle,
  IoTime,
  IoLockClosedOutline,
  IoShieldCheckmarkOutline,
  IoReturnUpBackOutline,
  IoChatbubbleEllipsesOutline,
  IoEllipseOutline,
  IoPricetagsOutline,
  IoCube,
  IoAlbumsOutline,
  IoPricetagOutline,
  IoReaderOutline,
  IoImagesOutline,
  IoImageOutline,
  IoRemoveOutline,
} from 'react-icons/io5'

const ICONS = {
  storefront: IoStorefront,
  'storefront-outline': IoStorefrontOutline,
  'grid-outline': IoGridOutline,
  'business-outline': IoBusinessOutline,
  'cube-outline': IoCubeOutline,
  'list-outline': IoListOutline,
  'people-outline': IoPeopleOutline,
  'card-outline': IoCardOutline,
  'trending-up-outline': IoTrendingUpOutline,
  'settings-outline': IoSettingsOutline,
  'log-out-outline': IoLogOutOutline,
  'chevron-forward-outline': IoChevronForwardOutline,
  'chevron-back-outline': IoChevronBackOutline,
  'menu-outline': IoMenuOutline,
  'close-outline': IoCloseOutline,
  'search-outline': IoSearchOutline,
  'add-outline': IoAddOutline,
  'download-outline': IoDownloadOutline,
  'cash-outline': IoCashOutline,
  'receipt-outline': IoReceiptOutline,
  'globe-outline': IoGlobeOutline,
  'checkmark-circle': IoCheckmarkCircle,
  'checkmark-circle-outline': IoCheckmarkCircleOutline,
  'close-circle-outline': IoCloseCircleOutline,
  'alert-circle-outline': IoAlertCircleOutline,
  'information-circle-outline': IoInformationCircleOutline,
  'arrow-down-circle': IoArrowDownCircle,
  'arrow-up-circle': IoArrowUpCircle,
  'arrow-down-circle-outline': IoArrowDownCircleOutline,
  'arrow-up-circle-outline': IoArrowUpCircleOutline,
  'arrow-back-outline': IoArrowBackOutline,
  'time-outline': IoTimeOutline,
  'layers-outline': IoLayersOutline,
  'pause-circle-outline': IoPauseCircleOutline,
  'eye-outline': IoEyeOutline,
  'create-outline': IoCreateOutline,
  'person-outline': IoPersonOutline,
  'person-circle-outline': IoPersonCircleOutline,
  'person-add-outline': IoPersonAddOutline,
  'qr-code-outline': IoQrCodeOutline,
  'bicycle-outline': IoBicycleOutline,
  'swap-horizontal-outline': IoSwapHorizontalOutline,
  'refresh-outline': IoRefreshOutline,
  'print-outline': IoPrintOutline,
  'return-down-back-outline': IoReturnDownBackOutline,
  'document-text-outline': IoDocumentTextOutline,
  'call-outline': IoCallOutline,
  'share-social-outline': IoShareSocialOutline,
  'camera-outline': IoCameraOutline,
  'scan-outline': IoScanOutline,
  'barcode-outline': IoBarcodeOutline,
  'trash-outline': IoTrashOutline,
  'mail-outline': IoMailOutline,
  'location-outline': IoLocationOutline,
  'logo-facebook': IoLogoFacebook,
  'logo-instagram': IoLogoInstagram,
  'logo-linkedin': IoLogoLinkedin,
  'logo-youtube': IoLogoYoutube,
  'musical-notes-outline': IoMusicalNotesOutline,
  'play-circle-outline': IoPlayCircleOutline,
  'locate-outline': IoLocateOutline,
  'warning-outline': IoWarningOutline,
  'arrow-up-outline': IoArrowUpOutline,
  'arrow-forward-outline': IoArrowForwardOutline,
  'map-outline': IoMapOutline,
  location: IoLocation,
  'sync-outline': IoSyncOutline,
  'key-outline': IoKeyOutline,
  'chevron-down-outline': IoChevronDownOutline,
  'ellipsis-vertical': IoEllipsisVertical,
  'add-circle-outline': IoAddCircleOutline,
  'eye-off-outline': IoEyeOffOutline,
  'cloud-upload-outline': IoCloudUploadOutline,
  'leaf-outline': IoLeafOutline,
  'rocket-outline': IoRocketOutline,
  'checkmark-outline': IoCheckmarkOutline,
  'calendar-outline': IoCalendarOutline,
  'document-outline': IoDocumentOutline,
  'close-circle': IoCloseCircle,
  time: IoTime,
  'lock-closed-outline': IoLockClosedOutline,
  'shield-checkmark-outline': IoShieldCheckmarkOutline,
  'return-up-back-outline': IoReturnUpBackOutline,
  'chatbubble-ellipses-outline': IoChatbubbleEllipsesOutline,
  'ellipse-outline': IoEllipseOutline,
  'pricetags-outline': IoPricetagsOutline,
  cube: IoCube,
  'albums-outline': IoAlbumsOutline,
  'pricetag-outline': IoPricetagOutline,
  'reader-outline': IoReaderOutline,
  'images-outline': IoImagesOutline,
  'image-outline': IoImageOutline,
  'remove-outline': IoRemoveOutline,
}

export default function Icon({ name, size, className = '', style = {}, ...rest }) {
  const Cmp = ICONS[name]
  if (!Cmp) {
    if (import.meta.env.DEV) console.warn(`Icon: unknown name "${name}"`)
    return null
  }
  const mergedStyle = size ? { fontSize: `${size}px`, ...style } : style
  return <Cmp className={className} style={mergedStyle} {...rest} />
}
